# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y curl python3 openjdk-8-jre unzip sudo bash ca-certificates iproute2 python3-apt aptitude && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash iproute && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python3 sudo bash iproute2 && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python3 sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python3 sudo bash ca-certificates iproute2 && xbps-remove -O; fi


RUN groupadd -r wildfly \
    && useradd -r -m -g wildfly -d /opt/wildfly wildfly 
WORKDIR /opt/wildfly
RUN curl -O https://download.jboss.org/wildfly/18.0.1.Final/wildfly-18.0.1.Final.zip
RUN unzip wildfly-18.0.1.Final.zip \
    && chown -R wildfly: wildfly-18.0.1.Final \
    && mv wildfly-18.0.1.Final/* . \
    && rm -rf wildfly-18.0.1.Final \
    && rm wildfly-18.0.1.Final.zip
RUN cp docs/contrib/scripts/init.d/wildfly-init-debian.sh /etc/init.d/wildfly \
    && chown root: /etc/init.d/wildfly
RUN cp docs/contrib/scripts/init.d/wildfly.conf /etc/default/wildfly \
    && chown root: /etc/default/wildfly
RUN echo "JBOSS_HOME=/opt/wildfly" >> /etc/default/wildfly
